backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

collections:
  - name: "galleryImages" # Used in routes, e.g., /admin/collections/blog
    label: "Images de la galerie" # Used in the UI
    folder: "src/pages/galleryItems" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      # TODO: rename “name” field. img-large would be more fitting. Then generate the thumbnail on the pipeline.
      - {label: "Image", name: "imgSrc", widget: "image"}
      - {label: "Nom de l'image (ne sera pas visible, utilisé pour les fichiers .md)", name: "name", widget: "string"}
      - {label: "Catégorie", name: "type", widget: "select", options: ["black-white", "colour", "drawing", "other"]}
      - {label: "Texte alternatif (ex : Peinture de chat)", name: "alt", widget: "string"}
      - {label: "Dimensions (ex : 200x200 cm)", name: "dimensions", widget: "string", required: false}
      - {label: "Prix (en €)", name: "price", widget: "number", required: false}